Ваш
выбор - {'items': [
    {'id': '83028213', 'premium': False, 'name': 'Диспетчер чатов, удаленно', 'department': None, 'has_test': False,
     'response_letter_required': False, 'area': {'id': '113', 'name': 'Россия', 'url': 'https://api.hh.ru/areas/113'},
     'salary': {'from': 26000, 'to': 40000, 'currency': 'RUR', 'gross': False},
     'type': {'id': 'open', 'name': 'Открытая'}, 'address': None, 'response_url': None, 'sort_point_distance': None,
     'published_at': '2023-07-05T12:54:40+0300', 'created_at': '2023-07-05T12:54:40+0300', 'archived': False,
     'apply_alternate_url': 'https://hh.ru/applicant/vacancy_response?vacancyId=83028213', 'insider_interview': None,
     'url': 'https://api.hh.ru/vacancies/83028213?host=hh.ru', 'alternate_url': 'https://hh.ru/vacancy/83028213',
     'relations': [], 'employer': {'id': '1740', 'name': 'Яндекс', 'url': 'https://api.hh.ru/employers/1740',
                                   'alternate_url': 'https://hh.ru/employer/1740',
                                   'logo_urls': {'90': 'https://hhcdn.ru/employer-logo/3790847.png',
                                                 '240': 'https://hhcdn.ru/employer-logo/3790848.png',
                                                 'original': 'https://hhcdn.ru/employer-logo-original/837491.png'},
                                   'vacancies_url': 'https://api.hh.ru/vacancies?employer_id=1740',
                                   'accredited_it_employer': False, 'trusted': True}, 'snippet': {
        'requirement': 'Опыт работы не требуется. Обязательно наличие ПК или ноутбука. Будет плюсом опыт работы на вакансиях:',
        'responsibility': None}, 'contacts': None, 'schedule': None, 'working_days': [], 'working_time_intervals': [],
     'working_time_modes': [{'id': 'start_after_sixteen', 'name': 'Можно начинать работать после 16:00'}],
     'accept_temporary': False, 'professional_roles': [{'id': '40', 'name': 'Другое'}],
     'accept_incomplete_resumes': True, 'experience': {'id': 'noExperience', 'name': 'Нет опыта'},
     'employment': {'id': 'full', 'name': 'Полная занятость'}, 'adv_response_url': None, 'is_adv_vacancy': False},
    {'id': '83028521', 'premium': False, 'name': 'Менеджер чатов на дому (в Яндекс)', 'department': None,
     'has_test': False, 'response_letter_required': False,
     'area': {'id': '113', 'name': 'Россия', 'url': 'https://api.hh.ru/areas/113'},
     'salary': {'from': 26000, 'to': 40000, 'currency': 'RUR', 'gross': False},
     'type': {'id': 'open', 'name': 'Открытая'}, 'address': None, 'response_url': None, 'sort_point_distance': None,
     'published_at': '2023-07-05T12:57:59+0300', 'created_at': '2023-07-05T12:57:59+0300', 'archived': False,
     'apply_alternate_url': 'https://hh.ru/applicant/vacancy_response?vacancyId=83028521', 'insider_interview': None,
     'url': 'https://api.hh.ru/vacancies/83028521?host=hh.ru', 'alternate_url': 'https://hh.ru/vacancy/83028521',
     'relations': [], 'employer': {'id': '1740', 'name': 'Яндекс', 'url': 'https://api.hh.ru/employers/1740',
                                   'alternate_url': 'https://hh.ru/employer/1740',
                                   'logo_urls': {'90': 'https://hhcdn.ru/employer-logo/3790847.png',
                                                 '240': 'https://hhcdn.ru/employer-logo/3790848.png',
                                                 'original': 'https://hhcdn.ru/employer-logo-original/837491.png'},
                                   'vacancies_url': 'https://api.hh.ru/vacancies?employer_id=1740',
                                   'accredited_it_employer': False, 'trusted': True}, 'snippet': {
        'requirement': 'Способен работать в команде. Способен принимать решения самостоятельно. Готов учиться и узнавать новое. Опыт работы в колл-центре или службе...',
        'responsibility': 'Работать с клиентами или партнерами для решения разнообразных ситуаций. Совершать звонки по их обращениям и давать письменные ответы. '},
     'contacts': None, 'schedule': None, 'working_days': [], 'working_time_intervals': [],
     'working_time_modes': [{'id': 'start_after_sixteen', 'name': 'Можно начинать работать после 16:00'}],
     'accept_temporary': False, 'professional_roles': [{'id': '40', 'name': 'Другое'}],
     'accept_incomplete_resumes': False, 'experience': {'id': 'noExperience', 'name': 'Нет опыта'},
     'employment': {'id': 'full', 'name': 'Полная занятость'}, 'adv_response_url': None, 'is_adv_vacancy': False},
    {'id': '83029101', 'premium': False, 'name': 'Удаленный диспетчер чатов (в Яндекс)', 'department': None,
     'has_test': False, 'response_letter_required': False,
     'area': {'id': '113', 'name': 'Россия', 'url': 'https://api.hh.ru/areas/113'},
     'salary': {'from': 26000, 'to': 40000, 'currency': 'RUR', 'gross': False},
     'type': {'id': 'open', 'name': 'Открытая'}, 'address': None, 'response_url': None, 'sort_point_distance': None,
     'published_at': '2023-07-05T13:06:28+0300', 'created_at': '2023-07-05T13:06:28+0300', 'archived': False,
     'apply_alternate_url': 'https://hh.ru/applicant/vacancy_response?vacancyId=83029101', 'insider_interview': None,
     'url': 'https://api.hh.ru/vacancies/83029101?host=hh.ru', 'alternate_url': 'https://hh.ru/vacancy/83029101',
     'relations': [], 'employer': {'id': '1740', 'name': 'Яндекс', 'url': 'https://api.hh.ru/employers/1740',
                                   'alternate_url': 'https://hh.ru/employer/1740',
                                   'logo_urls': {'90': 'https://hhcdn.ru/employer-logo/3790847.png',
                                                 '240': 'https://hhcdn.ru/employer-logo/3790848.png',
                                                 'original': 'https://hhcdn.ru/employer-logo-original/837491.png'},
                                   'vacancies_url': 'https://api.hh.ru/vacancies?employer_id=1740',
                                   'accredited_it_employer': False, 'trusted': True}, 'snippet': {
        'requirement': 'Способен работать в команде. Способен принимать решения самостоятельно. Готов учиться и узнавать новое. Опыт работы в колл-центре или службе...',
        'responsibility': 'Работать с клиентами или партнерами для решения разнообразных ситуаций. Совершать звонки по их обращениям и давать письменные ответы. '},
     'contacts': None, 'schedule': None, 'working_days': [], 'working_time_intervals': [],
     'working_time_modes': [{'id': 'start_after_sixteen', 'name': 'Можно начинать работать после 16:00'}],
     'accept_temporary': False, 'professional_roles': [{'id': '40', 'name': 'Другое'}],
     'accept_incomplete_resumes': True, 'experience': {'id': 'noExperience', 'name': 'Нет опыта'},
     'employment': {'id': 'full', 'name': 'Полная занятость'}, 'adv_response_url': None, 'is_adv_vacancy': False},
    {'id': '83028773', 'premium': False, 'name': 'Менеджер чатов, удалённо (в Яндекс)', 'department': None,
     'has_test': False, 'response_letter_required': False,
     'area': {'id': '113', 'name': 'Россия', 'url': 'https://api.hh.ru/areas/113'},
     'salary': {'from': 26000, 'to': 40000, 'currency': 'RUR', 'gross': False},
     'type': {'id': 'open', 'name': 'Открытая'}, 'address': None, 'response_url': None, 'sort_point_distance': None,
     'published_at': '2023-07-05T13:02:29+0300', 'created_at': '2023-07-05T13:02:29+0300', 'archived': False,
     'apply_alternate_url': 'https://hh.ru/applicant/vacancy_response?vacancyId=83028773', 'insider_interview': None,
     'url': 'https://api.hh.ru/vacancies/83028773?host=hh.ru', 'alternate_url': 'https://hh.ru/vacancy/83028773',
     'relations': [], 'employer': {'id': '1740', 'name': 'Яндекс', 'url': 'https://api.hh.ru/employers/1740',
                                   'alternate_url': 'https://hh.ru/employer/1740',
                                   'logo_urls': {'90': 'https://hhcdn.ru/employer-logo/3790847.png',
                                                 '240': 'https://hhcdn.ru/employer-logo/3790848.png',
                                                 'original': 'https://hhcdn.ru/employer-logo-original/837491.png'},
                                   'vacancies_url': 'https://api.hh.ru/vacancies?employer_id=1740',
                                   'accredited_it_employer': False, 'trusted': True}, 'snippet': {
        'requirement': 'Способен работать в команде. Способен принимать решения самостоятельно. Готов учиться и узнавать новое. Опыт работы в колл-центре или службе...',
        'responsibility': 'Работать с клиентами или партнерами для решения разнообразных ситуаций. Совершать звонки по их обращениям и давать письменные ответы. '},
     'contacts': None, 'schedule': None, 'working_days': [], 'working_time_intervals': [],
     'working_time_modes': [{'id': 'start_after_sixteen', 'name': 'Можно начинать работать после 16:00'}],
     'accept_temporary': False, 'professional_roles': [{'id': '40', 'name': 'Другое'}],
     'accept_incomplete_resumes': True, 'experience': {'id': 'noExperience', 'name': 'Нет опыта'},
     'employment': {'id': 'full', 'name': 'Полная занятость'}, 'adv_response_url': None, 'is_adv_vacancy': False},
    {'id': '83027722', 'premium': False, 'name': 'Оператор на входящие сообщения (удаленно, в Яндекс)',
     'department': None, 'has_test': False, 'response_letter_required': False,
     'area': {'id': '113', 'name': 'Россия', 'url': 'https://api.hh.ru/areas/113'},
     'salary': {'from': 26000, 'to': 40000, 'currency': 'RUR', 'gross': False},
     'type': {'id': 'open', 'name': 'Открытая'}, 'address': None, 'response_url': None, 'sort_point_distance': None,
     'published_at': '2023-07-05T12:47:37+0300', 'created_at': '2023-07-05T12:47:37+0300', 'archived': False,
     'apply_alternate_url': 'https://hh.ru/applicant/vacancy_response?vacancyId=83027722', 'insider_interview': None,
     'url': 'https://api.hh.ru/vacancies/83027722?host=hh.ru', 'alternate_url': 'https://hh.ru/vacancy/83027722',
     'relations': [], 'employer': {'id': '1740', 'name': 'Яндекс', 'url': 'https://api.hh.ru/employers/1740',
                                   'alternate_url': 'https://hh.ru/employer/1740',
                                   'logo_urls': {'90': 'https://hhcdn.ru/employer-logo/3790847.png',
                                                 '240': 'https://hhcdn.ru/employer-logo/3790848.png',
                                                 'original': 'https://hhcdn.ru/employer-logo-original/837491.png'},
                                   'vacancies_url': 'https://api.hh.ru/vacancies?employer_id=1740',
                                   'accredited_it_employer': False, 'trusted': True}, 'snippet': {
        'requirement': 'Способен работать в команде. Способен принимать решения самостоятельно. Готов учиться и узнавать новое. Опыт работы в колл-центре или службе...',
        'responsibility': 'Работать с клиентами или партнерами для решения разнообразных ситуаций. Совершать звонки по их обращениям и давать письменные ответы. '},
     'contacts': None, 'schedule': None, 'working_days': [], 'working_time_intervals': [],
     'working_time_modes': [{'id': 'start_after_sixteen', 'name': 'Можно начинать работать после 16:00'}],
     'accept_temporary': False, 'professional_roles': [{'id': '40', 'name': 'Другое'}],
     'accept_incomplete_resumes': True, 'experience': {'id': 'noExperience', 'name': 'Нет опыта'},
     'employment': {'id': 'full', 'name': 'Полная занятость'}, 'adv_response_url': None, 'is_adv_vacancy': False},
    {'id': '82727044', 'premium': False, 'name': 'Менеджер В2В продаж 2GIS', 'department': None, 'has_test': False,
     'response_letter_required': False,
     'area': {'id': '180', 'name': 'Петропавловск', 'url': 'https://api.hh.ru/areas/180'},
     'salary': {'from': 250000, 'to': None, 'currency': 'KZT', 'gross': False},
     'type': {'id': 'open', 'name': 'Открытая'},
     'address': {'city': 'Петропавловск', 'street': 'улица Карима Сутюшева', 'building': '60', 'lat': 54.865347,
                 'lng': 69.133158, 'description': None, 'raw': 'Петропавловск, улица Карима Сутюшева, 60',
                 'metro': None, 'metro_stations': [], 'id': '11100626'}, 'response_url': None,
     'sort_point_distance': None, 'published_at': '2023-06-29T09:28:37+0300', 'created_at': '2023-06-29T09:28:37+0300',
     'archived': False, 'apply_alternate_url': 'https://hh.ru/applicant/vacancy_response?vacancyId=82727044',
     'insider_interview': None, 'url': 'https://api.hh.ru/vacancies/82727044?host=hh.ru',
     'alternate_url': 'https://hh.ru/vacancy/82727044', 'relations': [],
     'employer': {'id': '3383137', 'name': '2GIS-SEVER.KZ', 'url': 'https://api.hh.ru/employers/3383137',
                  'alternate_url': 'https://hh.ru/employer/3383137',
                  'logo_urls': {'90': 'https://hhcdn.ru/employer-logo/3401729.png',
                                '240': 'https://hhcdn.ru/employer-logo/3401730.png',
                                'original': 'https://hhcdn.ru/employer-logo-original/740188.png'},
                  'vacancies_url': 'https://api.hh.ru/vacancies?employer_id=3383137', 'accredited_it_employer': False,
                  'trusted': True}, 'snippet': {
        'requirement': 'Получали образование в сфере менеджмента/сервиса и туризма. Если Вы имеете опыт работы в сфере услуг, опыт ведения переговоров, либо...',
        'responsibility': 'Работа по готовой клиентской базе и с новыми клиентами. Ведение переговоров, как по телефону и в личном формате. '},
     'contacts': None, 'schedule': None, 'working_days': [], 'working_time_intervals': [], 'working_time_modes': [],
     'accept_temporary': False,
     'professional_roles': [{'id': '70', 'name': 'Менеджер по продажам, менеджер по работе с клиентами'}],
     'accept_incomplete_resumes': False, 'experience': {'id': 'between1And3', 'name': 'От 1 года до 3 лет'},
     'employment': {'id': 'full', 'name': 'Полная занятость'}, 'adv_response_url': None, 'is_adv_vacancy': False},
    {'id': '82901691', 'premium': False, 'name': 'Менеджер по продажам услуг', 'department': None, 'has_test': False,
     'response_letter_required': False, 'area': {'id': '1002', 'name': 'Минск', 'url': 'https://api.hh.ru/areas/1002'},
     'salary': {'from': 1500, 'to': None, 'currency': 'BYR', 'gross': False},
     'type': {'id': 'open', 'name': 'Открытая'},
     'address': {'city': 'Минск', 'street': 'Мястровская улица', 'building': '26', 'lat': 53.940075, 'lng': 27.464831,
                 'description': None, 'raw': 'Минск, Мястровская улица, 26',
                 'metro': {'station_name': 'Кунцевщина', 'line_name': 'Автозаводская', 'station_id': '63.417',
                           'line_id': '63', 'lat': 53.906236, 'lng': 27.453916}, 'metro_stations': [
             {'station_name': 'Кунцевщина', 'line_name': 'Автозаводская', 'station_id': '63.417', 'line_id': '63',
              'lat': 53.906236, 'lng': 27.453916},
             {'station_name': 'Немига', 'line_name': 'Автозаводская', 'station_id': '63.422', 'line_id': '63',
              'lat': 53.905615, 'lng': 27.55415},
             {'station_name': 'Пушкинская', 'line_name': 'Автозаводская', 'station_id': '63.419', 'line_id': '63',
              'lat': 53.909519, 'lng': 27.495499}], 'id': '3659230'}, 'response_url': None, 'sort_point_distance': None,
     'published_at': '2023-07-03T10:39:09+0300', 'created_at': '2023-07-03T10:39:09+0300', 'archived': False,
     'apply_alternate_url': 'https://hh.ru/applicant/vacancy_response?vacancyId=82901691', 'insider_interview': None,
     'url': 'https://api.hh.ru/vacancies/82901691?host=hh.ru', 'alternate_url': 'https://hh.ru/vacancy/82901691',
     'relations': [],
     'employer': {'id': '2968758', 'name': 'Смарт Конекшн', 'url': 'https://api.hh.ru/employers/2968758',
                  'alternate_url': 'https://hh.ru/employer/2968758', 'logo_urls': None,
                  'vacancies_url': 'https://api.hh.ru/vacancies?employer_id=2968758', 'accredited_it_employer': False,
                  'trusted': True}, 'snippet': {'requirement': '3. ПЛЮС:',
                                                'responsibility': 'Работать с горячей базой клиентов и интернет-заявками, предоставлять качественный, востребованный продукт. Постоянно учиться, чтобы стать высокоэффективным переговорщиком. '},
     'contacts': None, 'schedule': None, 'working_days': [], 'working_time_intervals': [], 'working_time_modes': [],
     'accept_temporary': False,
     'professional_roles': [{'id': '70', 'name': 'Менеджер по продажам, менеджер по работе с клиентами'}],
     'accept_incomplete_resumes': False, 'experience': {'id': 'noExperience', 'name': 'Нет опыта'},
     'employment': {'id': 'full', 'name': 'Полная занятость'}, 'adv_response_url': None, 'is_adv_vacancy': False},
    {'id': '81031105', 'premium': False, 'name': 'Менеджер по продажам', 'department': None, 'has_test': False,
     'response_letter_required': False, 'area': {'id': '159', 'name': 'Астана', 'url': 'https://api.hh.ru/areas/159'},
     'salary': {'from': 150000, 'to': 300000, 'currency': 'KZT', 'gross': False},
     'type': {'id': 'open', 'name': 'Открытая'}, 'address': None, 'response_url': None, 'sort_point_distance': None,
     'published_at': '2023-06-24T14:37:49+0300', 'created_at': '2023-06-24T14:37:49+0300', 'archived': False,
     'apply_alternate_url': 'https://hh.ru/applicant/vacancy_response?vacancyId=81031105', 'insider_interview': None,
     'url': 'https://api.hh.ru/vacancies/81031105?host=hh.ru', 'alternate_url': 'https://hh.ru/vacancy/81031105',
     'relations': [],
     'employer': {'id': '579612', 'name': 'Инвиво, Лаборатория', 'url': 'https://api.hh.ru/employers/579612',
                  'alternate_url': 'https://hh.ru/employer/579612',
                  'logo_urls': {'240': 'https://hhcdn.ru/employer-logo/4206869.jpeg',
                                '90': 'https://hhcdn.ru/employer-logo/4206868.jpeg',
                                'original': 'https://hhcdn.ru/employer-logo-original/941582.jpeg'},
                  'vacancies_url': 'https://api.hh.ru/vacancies?employer_id=579612', 'accredited_it_employer': False,
                  'trusted': True}, 'snippet': {
        'requirement': 'Образование средне-специальное, высшее (желательно медицинское). Опыт работы в сфере pharmacy или fmcg не менее 1 года (желательно). ',
        'responsibility': 'Поиск и привлечение новых клиентов. Работа с имеющейся базой. Работа с клиентами компании( с врачами и лпу). Выполнение личного плана...'},
     'contacts': None, 'schedule': None, 'working_days': [], 'working_time_intervals': [], 'working_time_modes': [],
     'accept_temporary': False, 'professional_roles': [{'id': '65', 'name': 'Медицинский представитель'}],
     'accept_incomplete_resumes': False, 'experience': {'id': 'noExperience', 'name': 'Нет опыта'},
     'employment': {'id': 'full', 'name': 'Полная занятость'}, 'adv_response_url': None, 'is_adv_vacancy': False},
    {'id': '71146889', 'premium': False, 'name': 'Санитарка/санитар стерилизационной (ЦСО) в стоматологическую клинику',
     'department': None, 'has_test': False, 'response_letter_required': False,
     'area': {'id': '104', 'name': 'Челябинск', 'url': 'https://api.hh.ru/areas/104'},
     'salary': {'from': 30000, 'to': None, 'currency': 'RUR', 'gross': False},
     'type': {'id': 'open', 'name': 'Открытая'}, 'address': None, 'response_url': None, 'sort_point_distance': None,
     'published_at': '2023-07-13T13:42:47+0300', 'created_at': '2023-07-13T13:42:47+0300', 'archived': False,
     'apply_alternate_url': 'https://hh.ru/applicant/vacancy_response?vacancyId=71146889', 'insider_interview': None,
     'url': 'https://api.hh.ru/vacancies/71146889?host=hh.ru', 'alternate_url': 'https://hh.ru/vacancy/71146889',
     'relations': [], 'employer': {'id': '2756592', 'name': 'Сити Смайл', 'url': 'https://api.hh.ru/employers/2756592',
                                   'alternate_url': 'https://hh.ru/employer/2756592', 'logo_urls': None,
                                   'vacancies_url': 'https://api.hh.ru/vacancies?employer_id=2756592',
                                   'accredited_it_employer': False, 'trusted': True},
     'snippet': {'requirement': 'Рассмотрим кандидатов без опыта работы в ЦСО, через обучение.',
                 'responsibility': 'прием использованных инструментов на стерилизацию из отделений стоматологической клиники. - предстерилизационная обработка использованного инструментария. - проведение стерилизации с соблюдением режима и требований...'},
     'contacts': None, 'schedule': None, 'working_days': [], 'working_time_intervals': [], 'working_time_modes': [],
     'accept_temporary': False, 'professional_roles': [{'id': '40', 'name': 'Другое'}],
     'accept_incomplete_resumes': True, 'experience': {'id': 'noExperience', 'name': 'Нет опыта'},
     'employment': {'id': 'full', 'name': 'Полная занятость'}, 'adv_response_url': None, 'is_adv_vacancy': False},
    {'id': '82512487', 'premium': False, 'name': 'Продавец', 'department': None, 'has_test': False,
     'response_letter_required': False, 'area': {'id': '1002', 'name': 'Минск', 'url': 'https://api.hh.ru/areas/1002'},
     'salary': {'from': 900, 'to': 1500, 'currency': 'BYR', 'gross': False}, 'type': {'id': 'open', 'name': 'Открытая'},
     'address': None, 'response_url': None, 'sort_point_distance': None, 'published_at': '2023-06-27T10:04:20+0300',
     'created_at': '2023-06-27T10:04:20+0300', 'archived': False,
     'apply_alternate_url': 'https://hh.ru/applicant/vacancy_response?vacancyId=82512487', 'insider_interview': None,
     'url': 'https://api.hh.ru/vacancies/82512487?host=hh.ru', 'alternate_url': 'https://hh.ru/vacancy/82512487',
     'relations': [], 'employer': {'id': '894819', 'name': 'Сделай сам', 'url': 'https://api.hh.ru/employers/894819',
                                   'alternate_url': 'https://hh.ru/employer/894819',
                                   'logo_urls': {'90': 'https://hhcdn.ru/employer-logo/996635.jpeg',
                                                 'original': 'https://hhcdn.ru/employer-logo-original/121315.jpg',
                                                 '240': 'https://hhcdn.ru/employer-logo/996636.jpeg'},
                                   'vacancies_url': 'https://api.hh.ru/vacancies?employer_id=894819',
                                   'accredited_it_employer': False, 'trusted': True}, 'snippet': {
        'requirement': 'Максимальный уровень заработной платы указан для кандидатов с опытом работы и знанием товара (одна из групп - строительные материалы, сантехника, электрика...',
        'responsibility': None}, 'contacts': None, 'schedule': None, 'working_days': [], 'working_time_intervals': [],
     'working_time_modes': [], 'accept_temporary': False,
     'professional_roles': [{'id': '97', 'name': 'Продавец-консультант, продавец-кассир'}],
     'accept_incomplete_resumes': False, 'experience': {'id': 'noExperience', 'name': 'Нет опыта'},
     'employment': {'id': 'full', 'name': 'Полная занятость'}, 'adv_response_url': None, 'is_adv_vacancy': False},
    {'id': '83119280', 'premium': False, 'name': 'Продавец-консультант', 'department': None, 'has_test': False,
     'response_letter_required': False, 'area': {'id': '1002', 'name': 'Минск', 'url': 'https://api.hh.ru/areas/1002'},
     'salary': {'from': 1200, 'to': 1900, 'currency': 'BYR', 'gross': False},
     'type': {'id': 'open', 'name': 'Открытая'},
     'address': {'city': 'Минск', 'street': 'проспект Независимости', 'building': '58', 'lat': 53.917846,
                 'lng': 27.58914, 'description': None, 'raw': 'Минск, проспект Независимости, 58',
                 'metro': {'station_name': 'Академия наук', 'line_name': 'Московская', 'station_id': '62.407',
                           'line_id': '62', 'lat': 53.92187, 'lng': 27.599066}, 'metro_stations': [
             {'station_name': 'Академия наук', 'line_name': 'Московская', 'station_id': '62.407', 'line_id': '62',
              'lat': 53.92187, 'lng': 27.599066},
             {'station_name': 'Площадь Якуба Коласа', 'line_name': 'Московская', 'station_id': '62.408',
              'line_id': '62', 'lat': 53.915369, 'lng': 27.583265}], 'id': '4507350'}, 'response_url': None,
     'sort_point_distance': None, 'published_at': '2023-07-07T00:50:36+0300', 'created_at': '2023-07-07T00:50:36+0300',
     'archived': False, 'apply_alternate_url': 'https://hh.ru/applicant/vacancy_response?vacancyId=83119280',
     'insider_interview': None, 'url': 'https://api.hh.ru/vacancies/83119280?host=hh.ru',
     'alternate_url': 'https://hh.ru/vacancy/83119280', 'relations': [],
     'employer': {'id': '4953100', 'name': 'Сороквашин А. А.', 'url': 'https://api.hh.ru/employers/4953100',
                  'alternate_url': 'https://hh.ru/employer/4953100',
                  'logo_urls': {'original': 'https://hhcdn.ru/employer-logo-original/1125490.png',
                                '90': 'https://hhcdn.ru/employer-logo/6122549.png',
                                '240': 'https://hhcdn.ru/employer-logo/6122550.png'},
                  'vacancies_url': 'https://api.hh.ru/vacancies?employer_id=4953100', 'accredited_it_employer': False,
                  'trusted': True}, 'snippet': {
        'requirement': 'Любить людей, общение с ними. Желание и возможность проявляться, не бояться быть активным и инициативным членом команды. Любить людей (да...',
        'responsibility': 'Продажа товара на зале в магазине и консультирование клиентов по геологической и эзотерической составляющей. Работа с кассой. Подготовка и выкладка...'},
     'contacts': None, 'schedule': None, 'working_days': [], 'working_time_intervals': [], 'working_time_modes': [],
     'accept_temporary': False,
     'professional_roles': [{'id': '70', 'name': 'Менеджер по продажам, менеджер по работе с клиентами'}],
     'accept_incomplete_resumes': False, 'experience': {'id': 'between1And3', 'name': 'От 1 года до 3 лет'},
     'employment': {'id': 'full', 'name': 'Полная занятость'}, 'adv_response_url': None, 'is_adv_vacancy': False},
    {'id': '83374585', 'premium': False, 'name': 'Старший юрист', 'department': None, 'has_test': False,
     'response_letter_required': False, 'area': {'id': '159', 'name': 'Астана', 'url': 'https://api.hh.ru/areas/159'},
     'salary': {'from': 1500000, 'to': 2500000, 'currency': 'KZT', 'gross': True},
     'type': {'id': 'open', 'name': 'Открытая'}, 'address': None, 'response_url': None, 'sort_point_distance': None,
     'published_at': '2023-07-13T09:53:16+0300', 'created_at': '2023-07-13T09:53:16+0300', 'archived': False,
     'apply_alternate_url': 'https://hh.ru/applicant/vacancy_response?vacancyId=83374585', 'insider_interview': None,
     'url': 'https://api.hh.ru/vacancies/83374585?host=hh.ru', 'alternate_url': 'https://hh.ru/vacancy/83374585',
     'relations': [], 'employer': {'id': '2843617', 'name': 'CentraCore', 'url': 'https://api.hh.ru/employers/2843617',
                                   'alternate_url': 'https://hh.ru/employer/2843617', 'logo_urls': None,
                                   'vacancies_url': 'https://api.hh.ru/vacancies?employer_id=2843617',
                                   'accredited_it_employer': False, 'trusted': True}, 'snippet': {
        'requirement': 'Общий стаж работы по юридической специальности не менее 7-10 лет (наличие опыта в консалтинговых фирмах приветствуется). Высшее юридическое образование...',
        'responsibility': 'Договорная работа - подготовка, проверка, комментирование различных видов гражданско-правовых договоров. Корпоративная работа - сопровождение создания, перерегистрации, преобразования и ликвидации юридических лиц...'},
     'contacts': None, 'schedule': None, 'working_days': [], 'working_time_intervals': [], 'working_time_modes': [],
     'accept_temporary': False, 'professional_roles': [{'id': '145', 'name': 'Юрисконсульт'}],
     'accept_incomplete_resumes': False, 'experience': {'id': 'moreThan6', 'name': 'Более 6 лет'},
     'employment': {'id': 'full', 'name': 'Полная занятость'}, 'adv_response_url': None, 'is_adv_vacancy': False},
    {'id': '81011506', 'premium': False,
     'name': 'Менеджер по работе с клиентами / Специалист по обработке входящих заявок', 'department': None,
     'has_test': False, 'response_letter_required': False,
     'area': {'id': '1002', 'name': 'Минск', 'url': 'https://api.hh.ru/areas/1002'},
     'salary': {'from': 1150, 'to': 1300, 'currency': 'BYR', 'gross': False},
     'type': {'id': 'open', 'name': 'Открытая'},
     'address': {'city': 'Минск', 'street': 'улица Притыцкого', 'building': '156', 'lat': 53.908649, 'lng': 27.432321,
                 'description': None, 'raw': 'Минск, улица Притыцкого, 156',
                 'metro': {'station_name': 'Каменная Горка', 'line_name': 'Автозаводская', 'station_id': '63.416',
                           'line_id': '63', 'lat': 53.90683, 'lng': 27.437558}, 'metro_stations': [
             {'station_name': 'Каменная Горка', 'line_name': 'Автозаводская', 'station_id': '63.416', 'line_id': '63',
              'lat': 53.90683, 'lng': 27.437558}], 'id': '1215153'}, 'response_url': None, 'sort_point_distance': None,
     'published_at': '2023-06-24T11:11:41+0300', 'created_at': '2023-06-24T11:11:41+0300', 'archived': False,
     'apply_alternate_url': 'https://hh.ru/applicant/vacancy_response?vacancyId=81011506', 'insider_interview': None,
     'url': 'https://api.hh.ru/vacancies/81011506?host=hh.ru', 'alternate_url': 'https://hh.ru/vacancy/81011506',
     'relations': [],
     'employer': {'id': '2312754', 'name': 'Импорт-центр Запад', 'url': 'https://api.hh.ru/employers/2312754',
                  'alternate_url': 'https://hh.ru/employer/2312754',
                  'logo_urls': {'original': 'https://hhcdn.ru/employer-logo-original/796270.png',
                                '90': 'https://hhcdn.ru/employer-logo/3625967.png',
                                '240': 'https://hhcdn.ru/employer-logo/3625968.png'},
                  'vacancies_url': 'https://api.hh.ru/vacancies?employer_id=2312754', 'accredited_it_employer': False,
                  'trusted': True}, 'snippet': {
        'requirement': 'Уверенный пользователь ПК. Навыки делового общения. Грамотная устная и письменная речь. Дисциплинированность. Умение планировать свой рабочий день и время. ',
        'responsibility': 'Обработка входящих заявок по готовому скрипту. Выявление потребности клиентов при входящих обращениях. Разбор входящих обращений по воронкам. Работа с данными...'},
     'contacts': None, 'schedule': None, 'working_days': [], 'working_time_intervals': [], 'working_time_modes': [],
     'accept_temporary': True,
     'professional_roles': [{'id': '70', 'name': 'Менеджер по продажам, менеджер по работе с клиентами'}],
     'accept_incomplete_resumes': True, 'experience': {'id': 'between1And3', 'name': 'От 1 года до 3 лет'},
     'employment': {'id': 'full', 'name': 'Полная занятость'}, 'adv_response_url': None, 'is_adv_vacancy': False},
    {'id': '82282113', 'premium': False, 'name': 'Продавец', 'department': None, 'has_test': False,
     'response_letter_required': False, 'area': {'id': '159', 'name': 'Астана', 'url': 'https://api.hh.ru/areas/159'},
     'salary': {'from': 250000, 'to': 290000, 'currency': 'KZT', 'gross': False},
     'type': {'id': 'open', 'name': 'Открытая'},
     'address': {'city': 'Нур-Султан (Астана)', 'street': 'проспект Рахимжана Кошкарбаева', 'building': '2',
                 'lat': 51.128252, 'lng': 71.461331, 'description': None,
                 'raw': 'Нур-Султан (Астана), проспект Рахимжана Кошкарбаева, 2', 'metro': None, 'metro_stations': [],
                 'id': '4179120'}, 'response_url': None, 'sort_point_distance': None,
     'published_at': '2023-06-22T11:24:28+0300', 'created_at': '2023-06-22T11:24:28+0300', 'archived': False,
     'apply_alternate_url': 'https://hh.ru/applicant/vacancy_response?vacancyId=82282113', 'insider_interview': None,
     'url': 'https://api.hh.ru/vacancies/82282113?host=hh.ru', 'alternate_url': 'https://hh.ru/vacancy/82282113',
     'relations': [],
     'employer': {'id': '2472409', 'name': 'Punto (Пунто)', 'url': 'https://api.hh.ru/employers/2472409',
                  'alternate_url': 'https://hh.ru/employer/2472409', 'logo_urls': None,
                  'vacancies_url': 'https://api.hh.ru/vacancies?employer_id=2472409', 'accredited_it_employer': False,
                  'trusted': True}, 'snippet': {'requirement': None, 'responsibility': None}, 'contacts': None,
     'schedule': None, 'working_days': [], 'working_time_intervals': [], 'working_time_modes': [],
     'accept_temporary': False, 'professional_roles': [{'id': '97', 'name': 'Продавец-консультант, продавец-кассир'}],
     'accept_incomplete_resumes': True, 'experience': {'id': 'noExperience', 'name': 'Нет опыта'},
     'employment': {'id': 'full', 'name': 'Полная занятость'}, 'adv_response_url': None, 'is_adv_vacancy': False},
    {'id': '83275140', 'premium': False, 'name': 'Главный бухгалтер', 'department': None, 'has_test': False,
     'response_letter_required': False, 'area': {'id': '1002', 'name': 'Минск', 'url': 'https://api.hh.ru/areas/1002'},
     'salary': {'from': 5000, 'to': None, 'currency': 'BYR', 'gross': False},
     'type': {'id': 'open', 'name': 'Открытая'},
     'address': {'city': 'Минск', 'street': 'проспект Пушкина', 'building': '39', 'lat': 53.908257, 'lng': 27.493945,
                 'description': None, 'raw': 'Минск, проспект Пушкина, 39',
                 'metro': {'station_name': 'Пушкинская', 'line_name': 'Автозаводская', 'station_id': '63.419',
                           'line_id': '63', 'lat': 53.909519, 'lng': 27.495499}, 'metro_stations': [
             {'station_name': 'Пушкинская', 'line_name': 'Автозаводская', 'station_id': '63.419', 'line_id': '63',
              'lat': 53.909519, 'lng': 27.495499}], 'id': '13745597'}, 'response_url': None,
     'sort_point_distance': None, 'published_at': '2023-07-11T12:06:11+0300', 'created_at': '2023-07-11T12:06:11+0300',
     'archived': False, 'apply_alternate_url': 'https://hh.ru/applicant/vacancy_response?vacancyId=83275140',
     'insider_interview': None, 'url': 'https://api.hh.ru/vacancies/83275140?host=hh.ru',
     'alternate_url': 'https://hh.ru/vacancy/83275140', 'relations': [],
     'employer': {'id': '4157750', 'name': 'ВуденКит', 'url': 'https://api.hh.ru/employers/4157750',
                  'alternate_url': 'https://hh.ru/employer/4157750', 'logo_urls': None,
                  'vacancies_url': 'https://api.hh.ru/vacancies?employer_id=4157750', 'accredited_it_employer': False,
                  'trusted': True}, 'snippet': {
        'requirement': 'Знания бухгалтерского учета со стороны застройщика и бухгалтерского учета по сдаче в аренду специальной техники. Опыт работы в строительных организациях...',
        'responsibility': 'Налогообложение. ВЭД. Отчеты ФСЗН, Белгосстрах, Статистика. ЭСЧФ.'}, 'contacts': None,
     'schedule': None, 'working_days': [], 'working_time_intervals': [], 'working_time_modes': [],
     'accept_temporary': False, 'professional_roles': [{'id': '18', 'name': 'Бухгалтер'}],
     'accept_incomplete_resumes': False, 'experience': {'id': 'moreThan6', 'name': 'Более 6 лет'},
     'employment': {'id': 'full', 'name': 'Полная занятость'}, 'adv_response_url': None, 'is_adv_vacancy': False},
    {'id': '83379750', 'premium': False, 'name': 'Бухгалтер', 'department': None, 'has_test': False,
     'response_letter_required': False, 'area': {'id': '1002', 'name': 'Минск', 'url': 'https://api.hh.ru/areas/1002'},
     'salary': {'from': 1900, 'to': None, 'currency': 'BYR', 'gross': False},
     'type': {'id': 'open', 'name': 'Открытая'},
     'address': {'city': 'деревня Цнянка', 'street': None, 'building': None, 'lat': 53.975073, 'lng': 27.532016,
                 'description': None, 'raw': 'деревня Цнянка', 'metro': None, 'metro_stations': [], 'id': '179995'},
     'response_url': None, 'sort_point_distance': None, 'published_at': '2023-07-13T11:01:18+0300',
     'created_at': '2023-07-13T11:01:18+0300', 'archived': False,
     'apply_alternate_url': 'https://hh.ru/applicant/vacancy_response?vacancyId=83379750', 'insider_interview': None,
     'url': 'https://api.hh.ru/vacancies/83379750?host=hh.ru', 'alternate_url': 'https://hh.ru/vacancy/83379750',
     'relations': [], 'employer': {'id': '1075075', 'name': 'БЕЛРОБОТ', 'url': 'https://api.hh.ru/employers/1075075',
                                   'alternate_url': 'https://hh.ru/employer/1075075',
                                   'logo_urls': {'original': 'https://hhcdn.ru/employer-logo-original/82374.bmp',
                                                 '90': 'https://hhcdn.ru/employer-logo/745139.png',
                                                 '240': 'https://hhcdn.ru/employer-logo/745140.png'},
                                   'vacancies_url': 'https://api.hh.ru/vacancies?employer_id=1075075',
                                   'accredited_it_employer': False, 'trusted': True}, 'snippet': {
        'requirement': 'Высшее или среднее специальное образование (экономическое или бухгалтерское). Знание и опыт работы в 1С8.3 (Хьюмен). ',
        'responsibility': 'Учет банковских операций по сч.51. Регистрация договоров. Учет прихода импорта из РФ. ЭСЧФ (выставление и подписание, обработка в 1...'},
     'contacts': None, 'schedule': None, 'working_days': [], 'working_time_intervals': [], 'working_time_modes': [],
     'accept_temporary': False, 'professional_roles': [{'id': '18', 'name': 'Бухгалтер'}],
     'accept_incomplete_resumes': False, 'experience': {'id': 'between3And6', 'name': 'От 3 до 6 лет'},
     'employment': {'id': 'full', 'name': 'Полная занятость'}, 'adv_response_url': None, 'is_adv_vacancy': False},
    {'id': '83046729', 'premium': False, 'name': 'Удаленный специалист службы поддержки', 'department': None,
     'has_test': False, 'response_letter_required': False,
     'area': {'id': '113', 'name': 'Россия', 'url': 'https://api.hh.ru/areas/113'},
     'salary': {'from': 26000, 'to': 40000, 'currency': 'RUR', 'gross': False},
     'type': {'id': 'open', 'name': 'Открытая'}, 'address': None, 'response_url': None, 'sort_point_distance': None,
     'published_at': '2023-07-05T16:16:14+0300', 'created_at': '2023-07-05T16:16:14+0300', 'archived': False,
     'apply_alternate_url': 'https://hh.ru/applicant/vacancy_response?vacancyId=83046729', 'insider_interview': None,
     'url': 'https://api.hh.ru/vacancies/83046729?host=hh.ru', 'alternate_url': 'https://hh.ru/vacancy/83046729',
     'relations': [], 'employer': {'id': '1740', 'name': 'Яндекс', 'url': 'https://api.hh.ru/employers/1740',
                                   'alternate_url': 'https://hh.ru/employer/1740',
                                   'logo_urls': {'90': 'https://hhcdn.ru/employer-logo/3790847.png',
                                                 '240': 'https://hhcdn.ru/employer-logo/3790848.png',
                                                 'original': 'https://hhcdn.ru/employer-logo-original/837491.png'},
                                   'vacancies_url': 'https://api.hh.ru/vacancies?employer_id=1740',
                                   'accredited_it_employer': False, 'trusted': True},
     'snippet': {'requirement': 'Умеет принимать самостоятельные решения.',
                 'responsibility': 'Работа с клиентами и партнерами для решения разнообразных ситуаций. Работа с входящими письменными обращениями во внутренней CRM-системе, редкие исходящие...'},
     'contacts': None, 'schedule': None, 'working_days': [], 'working_time_intervals': [],
     'working_time_modes': [{'id': 'start_after_sixteen', 'name': 'Можно начинать работать после 16:00'}],
     'accept_temporary': True, 'professional_roles': [{'id': '40', 'name': 'Другое'}],
     'accept_incomplete_resumes': True, 'experience': {'id': 'noExperience', 'name': 'Нет опыта'},
     'employment': {'id': 'full', 'name': 'Полная занятость'}, 'adv_response_url': None, 'is_adv_vacancy': False},
    {'id': '82124573', 'premium': False, 'name': 'QA manual инженер', 'department': None, 'has_test': False,
     'response_letter_required': False,
     'area': {'id': '2', 'name': 'Санкт-Петербург', 'url': 'https://api.hh.ru/areas/2'},
     'salary': {'from': 50000, 'to': 60000, 'currency': 'RUR', 'gross': False},
     'type': {'id': 'open', 'name': 'Открытая'}, 'address': None, 'response_url': None, 'sort_point_distance': None,
     'published_at': '2023-07-05T10:33:17+0300', 'created_at': '2023-07-05T10:33:17+0300', 'archived': False,
     'apply_alternate_url': 'https://hh.ru/applicant/vacancy_response?vacancyId=82124573', 'insider_interview': None,
     'url': 'https://api.hh.ru/vacancies/82124573?host=hh.ru', 'alternate_url': 'https://hh.ru/vacancy/82124573',
     'relations': [],
     'employer': {'id': '2365329', 'name': 'АпТрейдер (UpTrader)', 'url': 'https://api.hh.ru/employers/2365329',
                  'alternate_url': 'https://hh.ru/employer/2365329',
                  'logo_urls': {'240': 'https://hhcdn.ru/employer-logo/1775063.png',
                                '90': 'https://hhcdn.ru/employer-logo/1775062.png',
                                'original': 'https://hhcdn.ru/employer-logo-original/333178.png'},
                  'vacancies_url': 'https://api.hh.ru/vacancies?employer_id=2365329', 'accredited_it_employer': False,
                  'trusted': True}, 'snippet': {
        'requirement': 'Коммерческий опыт работы в тестировании от 6 месяцев. Опыт написания тест-кейсов. Опыт тестирования web-приложений, смежных систем, API. ',
        'responsibility': 'Контроль качества и тестирование web-приложений. Тестирование функций и интерфейсов сложной CRM-системы. Ведение тестовой документации. Регистрирование найденных ошибок в...'},
     'contacts': None, 'schedule': None, 'working_days': [], 'working_time_intervals': [], 'working_time_modes': [],
     'accept_temporary': False, 'professional_roles': [{'id': '124', 'name': 'Тестировщик'}],
     'accept_incomplete_resumes': False, 'experience': {'id': 'between1And3', 'name': 'От 1 года до 3 лет'},
     'employment': {'id': 'full', 'name': 'Полная занятость'}, 'adv_response_url': None, 'is_adv_vacancy': False},
    {'id': '83374698', 'premium': False, 'name': 'Главный бухгалтер', 'department': None, 'has_test': False,
     'response_letter_required': False, 'area': {'id': '1002', 'name': 'Минск', 'url': 'https://api.hh.ru/areas/1002'},
     'salary': {'from': 2500, 'to': 5000, 'currency': 'BYR', 'gross': False},
     'type': {'id': 'open', 'name': 'Открытая'}, 'address': None, 'response_url': None, 'sort_point_distance': None,
     'published_at': '2023-07-13T09:54:59+0300', 'created_at': '2023-07-13T09:54:59+0300', 'archived': False,
     'apply_alternate_url': 'https://hh.ru/applicant/vacancy_response?vacancyId=83374698', 'insider_interview': None,
     'url': 'https://api.hh.ru/vacancies/83374698?host=hh.ru', 'alternate_url': 'https://hh.ru/vacancy/83374698',
     'relations': [], 'employer': {'id': '1747931', 'name': 'Катран-М', 'url': 'https://api.hh.ru/employers/1747931',
                                   'alternate_url': 'https://hh.ru/employer/1747931', 'logo_urls': None,
                                   'vacancies_url': 'https://api.hh.ru/vacancies?employer_id=1747931',
                                   'accredited_it_employer': False, 'trusted': True}, 'snippet': {
        'requirement': 'Опыт работы бухгалтером от 6 лет. Внимательность, усидчивость, активность и желание получать новые знания. Любит работать с документами и ответственно...',
        'responsibility': 'Ведение бухгалтерского учета. Проверка и закрытие отчётного периода. Составление налоговой и бухгалтерской отчётности. Первичная учётная документация. Подготовка отчетности в налоговые...'},
     'contacts': None, 'schedule': None, 'working_days': [], 'working_time_intervals': [], 'working_time_modes': [],
     'accept_temporary': False, 'professional_roles': [{'id': '18', 'name': 'Бухгалтер'}],
     'accept_incomplete_resumes': False, 'experience': {'id': 'moreThan6', 'name': 'Более 6 лет'},
     'employment': {'id': 'full', 'name': 'Полная занятость'}, 'adv_response_url': None, 'is_adv_vacancy': False},
    {'id': '83246968', 'premium': False, 'name': 'Продавец-консультант', 'department': None, 'has_test': False,
     'response_letter_required': False, 'area': {'id': '1002', 'name': 'Минск', 'url': 'https://api.hh.ru/areas/1002'},
     'salary': {'from': 1500, 'to': 3000, 'currency': 'BYR', 'gross': False},
     'type': {'id': 'open', 'name': 'Открытая'}, 'address': None, 'response_url': None, 'sort_point_distance': None,
     'published_at': '2023-07-10T21:16:52+0300', 'created_at': '2023-07-10T21:16:52+0300', 'archived': False,
     'apply_alternate_url': 'https://hh.ru/applicant/vacancy_response?vacancyId=83246968', 'insider_interview': None,
     'url': 'https://api.hh.ru/vacancies/83246968?host=hh.ru', 'alternate_url': 'https://hh.ru/vacancy/83246968',
     'relations': [],
     'employer': {'id': '1176874', 'name': 'АльянсМакМаркет', 'url': 'https://api.hh.ru/employers/1176874',
                  'alternate_url': 'https://hh.ru/employer/1176874', 'logo_urls': None,
                  'vacancies_url': 'https://api.hh.ru/vacancies?employer_id=1176874', 'accredited_it_employer': False,
                  'trusted': True},
     'snippet': {'requirement': 'Опрятный внешний вид, коммуникабельность, стрессоустойчивость.',
                 'responsibility': 'Консультация клиентов на территории работодателя.'}, 'contacts': None,
     'schedule': None, 'working_days': [], 'working_time_intervals': [], 'working_time_modes': [],
     'accept_temporary': False, 'professional_roles': [{'id': '97', 'name': 'Продавец-консультант, продавец-кассир'}],
     'accept_incomplete_resumes': True, 'experience': {'id': 'noExperience', 'name': 'Нет опыта'},
     'employment': {'id': 'full', 'name': 'Полная занятость'}, 'adv_response_url': None, 'is_adv_vacancy': False}],
         'found': 1401108, 'pages': 100, 'per_page': 20, 'page': 0, 'clusters': None, 'arguments': None,
         'alternate_url': 'https://hh.ru/search/vacancy?enable_snippets=true'}
